version: "3"

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/mnadir/data/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/mnadir/data/mariadb
      o: bind
      type: none

networks:
  inception:
    name: inception
    driver: bridge

services:
  nginx:
    container_name: nginx
    build: requirements/nginx/.
    env_file:
      - .env
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: always
    init: true
  wordpress:
    container_name: wordpress
    build: requirements/wordpress/.
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: always
    init: true
  mariadb:
    container_name: mariadb
    build: requirements/mariadb/.
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always
    init: true
